### ISSUE TITLE
Paiement required

### ISSUE THREAD

**Issue by sylvainmetayer** [mlcdf/macbernik#28]
https://la-famille-pirate.now.sh/ 

@mlcdf Le site indique une erreur 402. Est-ce qu'il est possible de le déployer ailleurs (éventuellement sur Github pages, étant donné que ce n'est que du JS) ?

**Comment by mlcdf** [comment]
Et voilà : https://mlcdf.github.io/macbernik

J'ai dû rajouté `"use strict";` (à la main) au début du vendor.js afin que GitHub le considère comme un script et qu'il soit donc envoyé avec le bon MIME-TYPE. Je pense que l'algo qu'utilise GitHub pour déterminer le MIME-TYPE de fichiers a des soucis lorsque c'est des fichiers minifiés (on avait pas de problème avec l'ancien hébergeur).
